[providers]
node = "18"
python = "3.11"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm", "python311", "pip"]

[phases.build]
cmds = [
    "cd thinkaloudLM/frontend && npm install && npm run build",
    "cd thinkaloudLM/backend && pip install -r requirements.txt"
]

[phases.start]
cmd = "cd thinkaloudLM/backend && python run.py" 